# Generated by Django 5.0.4 on 2024-04-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_resource_body_alter_resource_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarouselImages', models.ImageField(blank=True, null=True, upload_to='CarouselImages')),
                ('body', models.TextField()),
            ],
        ),
    ]
