# Generated by Django 4.2.11 on 2024-04-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_resource_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
