# Generated by Django 4.2.11 on 2024-04-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_footerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='Calendar',
            field=models.DateField(blank=True, null=True),
        ),
    ]
