# Generated by Django 4.2.11 on 2024-04-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_location_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
